# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
# tasks file for roles/disk

- name: create disk
  vcd_disk:
    disk_name: "{{ disk_name }}"
    description: "Test Disk"
    size: "100"
    vdc: "Terraform_VDC"
    storage_profile: "Standard"
    state: "present"
  register: output

- name: create disk output
  debug:
    msg: '{{ output }}'

- name: update disk
  vcd_disk:
    disk_name: "{{ disk_name }}"
    new_disk_name: "{{ updated_disk_name }}"
    new_size: "200"
    vdc: "Terraform_VDC"
    new_storage_profile: "Standard"
    state: "update"
  register: output

- name: update disk output
  debug:
    msg: '{{ output }}'

- name: delete disk
  vcd_disk:
    disk_name: "{{ updated_disk_name }}"
    description: "Test Disk"
    vdc: "Terraform_VDC"
    state: "absent"
  register: output

- name: delete disk output
  debug:
    msg: '{{ output }}'
