# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only

---
# vars file for roles/catalogs
catalog_name: test_catalog_104
description: test_catalog_description_104
new_catalog_name: test_catalog_105

shared: true