---
# tasks file for vcd_vapp_vm_nic

- name: add vm nic
  vcd_vapp_vm_nic:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    vapp: vApp_system_2
    vm_name: centos
    vdc: ACME_PAYG
    network: acme_internal_direct
    ip_allocation_mode: DHCP
    is_connected: True
    adapter_type: E1000
    state: present
  register: output


- name: add vm nic output
  debug:
    msg: '{{ output }}'

- name: update vm nic
  vcd_vapp_vm_nic:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    vapp: vApp_system_2
    vm_name: centos
    vdc: ACME_PAYG
    network: acme_internal_direct
    is_primary: True
    state: update
  register: output


- name: update vm nic output
  debug:
    msg: '{{ output }}'

- name: power off vm
  vcd_vapp_vm:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    target_vapp: vApp_system_2
    target_vm_name: centos
    target_vdc: ACME_PAYG
    operation: poweroff
  register: output

- name: power off vm output
  debug:
    msg: '{{ output }}'


- name: delete vm nic
  vcd_vapp_vm_nic:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    vapp: vApp_system_2
    vm_name: centos
    vdc: ACME_PAYG
    nic_ids:
        - 1
    state: absent
  register: output


- name: delete vm nic output
  debug:
    msg: '{{ output }}'

- name: power on vm
  vcd_vapp_vm:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    target_vapp: vApp_system_2
    target_vm_name: centos
    target_vdc: ACME_PAYG
    operation: poweron
  register: output

- name: power on vm output
  debug:
    msg: '{{ output }}'

- name: read vm nics
  vcd_vapp_vm_nic:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    vapp: vApp_system_2
    vm_name: centos
    vdc: ACME_PAYG
    operation: read
  register: output


- name: read vm nic output
  debug:
    msg: '{{ output }}'