# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
# tasks file for roles/vappvmnic
- name: create vapp vm nic
  vcd_vapp_vm_nic:
     vm_name: "Tiny Linux template"
     vapp: "web2"
     vdc: "ACME_PAYG"
     network: "172.16.1.0"
     ip_allocation_mode: "MANUAL"
     ip_address: "172.16.1.121"
     state: "present"
  register: output

- name: create vapp vm nic output
  debug:
    msg: '{{ output }}'

- name: update nic
  vcd_vapp_vm_nic:
    vm_name: "Tiny Linux template"
    vapp: "web2"
    vdc: "ACME_PAYG"
    nic_id: 3
    ip_address: "172.16.1.122"
    state: "update"
  register: output

- name: update nic output
  debug:
    msg: '{{ output }}'

- name: read vapp vm nics
  vcd_vapp_vm_nic:
     vm_name: "Tiny Linux template"
     vapp: "web2"
     vdc: "ACME_PAYG"
     operation: "read"
  register: output

- name: read vapp vm nics output
  debug:
    msg: '{{ output }}'

- name: update nic
  vcd_vapp_vm_nic:
    vm_name: "Tiny Linux template"
    vapp: "web2"
    vdc: "ACME_PAYG"
    nic_id: 3
    network: "test_network"
    state: "update"
  register: output

- name: update nic output
  debug:
    msg: '{{ output }}'

- name: read vapp vm nics
  vcd_vapp_vm_nic:
     vm_name: "Tiny Linux template"
     vapp: "web2"
     vdc: "ACME_PAYG"
     operation: "read"
  register: output

- name: read vapp vm nics output
  debug:
    msg: '{{ output }}'

- name: update nic
  vcd_vapp_vm_nic:
    vm_name: "Tiny Linux template"
    vapp: "web2"
    vdc: "ACME_PAYG"
    nic_id: 3
    ip_allocation_mode: "DHCP"
    state: "update"
  register: output

- name: update nic output
  debug:
    msg: '{{ output }}'

- name: read vapp vm nics
  vcd_vapp_vm_nic:
     vm_name: "Tiny Linux template"
     vapp: "web2"
     vdc: "ACME_PAYG"
     operation: "read"
  register: output

- name: read vapp vm nics output
  debug:
    msg: '{{ output }}'

- name: update nic
  vcd_vapp_vm_nic:
    vm_name: "Tiny Linux template"
    vapp: "web2"
    vdc: "ACME_PAYG"
    nic_id: 3
    ip_allocation_mode: "MANUAL"
    ip_address: "172.16.1.122"
    network: "172.16.1.0"
    state: "update"
  register: output

- name: update nic output
  debug:
    msg: '{{ output }}'

- name: read vapp vm nics
  vcd_vapp_vm_nic:
     vm_name: "Tiny Linux template"
     vapp: "web2"
     vdc: "ACME_PAYG"
     operation: "read"
  register: output

- name: read vapp vm nics output
  debug:
    msg: '{{ output }}'

- name: delete nic
  vcd_vapp_vm_nic:
    vm_name: "Tiny Linux template"
    vapp: "web2"
    vdc: "ACME_PAYG"
    nic_ids:
      - 3
    state: "absent"
  register: output

- name: delete nic output
  debug:
    msg: '{{ output }}'

