# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
# tasks file for roles/vappnetwork

- name: add vapp network
  vcd_vapp_network:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    vdc: ACME_PAYG
    vapp: vApp_system_2
    network: sample_2
    network_cidr: 192.168.102.2/24
    primary_dns_ip: 192.168.102.1
    dns_suffix: dn
    ip_ranges:
      - 192.168.102.5-192.168.102.10
    is_guest_vlan_allowed: False
    state: present
  register: output

- name: add vapp network output
  debug:
    msg: "{{ output }}"

- name: read vapp networks
  vcd_vapp_network:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    vdc: ACME_PAYG
    vapp: vApp_system_2
    operation: read
  register: output

- name: read vapp networks output
  debug:
    msg: "{{ output }}"

- name: update vapp network
  vcd_vapp_network:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    vdc: ACME_PAYG
    vapp: vApp_system_2
    network: sample_2
    new_network: sample_3
    state: update
  register: output

- name: update vapp network output
  debug:
    msg: "{{ output }}"

- name: read vapp networks
  vcd_vapp_network:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    vdc: ACME_PAYG
    vapp: vApp_system_2
    operation: read
  register: output

- name: read vapp networks output
  debug:
    msg: "{{ output }}"

- name: delete vapp network
  vcd_vapp_network:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    vdc: ACME_PAYG
    vapp: vApp_system_2
    network: sample_3
    state: absent
  register: output

- name: delete vapp network output
  debug:
    msg: "{{ output }}"

- name: read vapp networks
  vcd_vapp_network:
    user: acmeadmin
    password: XXXXXXXXXX
    org: Acme
    vdc: ACME_PAYG
    vapp: vApp_system_2
    operation: read
  register: output

- name: read vapp networks output
  debug:
    msg: "{{ output }}"
