# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause OR GPL-3.0-only
---
# tasks file for roles/vapp
- name: instantiate vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    template_name: centos
    catalog_name: test_catalog_300
    vdc: ACME_PAYG
    power_on: False
    storage_profile: Standard
    state: present
  register: output

- name: instantiate vapp output
  debug:
    msg: '{{ output }}'

- name: create vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    power_on: False
    state: present
  register: output

- name: create vapp output
  debug:
    msg: '{{ output }}'

- name: power on vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    operation: poweron
  register: output

- name: power on vapp output
  debug:
    msg: '{{ output }}'

- name: power on vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    operation: poweron
  register: output

- name: power on vapp output
  debug:
    msg: '{{ output }}'

- name: power off vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG"
    operation: poweroff
  register: output

- name: power off vapp output
  debug:
    msg: '{{ output }}'

- name: power off vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    operation: poweroff
  register: output

- name: power off vapp output
  debug:
    msg: '{{ output }}'

- name: undeploy vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    operation: undeploy
  register: output

- name: undeploy vapp output
  debug:
    msg: '{{ output }}'

- name: undeploy vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    operation: undeploy
  register: output

- name: undeploy vapp output
  debug:
    msg: '{{ output }}'

- name: deploy vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    operation: deploy
  register: output

- name: deploy vapp output
  debug:
    msg: '{{ output }}'

- name: deploy vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    operation: deploy
  register: output

- name: deploy vapp output
  debug:
    msg: '{{ output }}'

- name: get list of vms
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    operation: list_vms
  register: output

- name: get list of vms output
  debug:
    msg: '{{ output }}'

- name: get list of networks
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    operation: list_networks
  register: output

- name: get list of networks output
  debug:
    msg: '{{ output }}'

- name: share vapp
  vcd_vapp:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vapp_name: test_vapp
    vdc: ACME_PAYG
    operation: share
  register: output

- name: share vapp output
  debug:
    msg: '{{ output }}'

- name: unshare vapp
  vcd_vapp:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vapp_name: acme_vapp
    vdc: ACME_PAYG
    operation: unshare
  register: output

- name: unshare vapp output
  debug:
    msg: '{{ output }}'

- name: set vapp metadata
  vcd_vapp:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vapp_name: acme_vapp
    vdc: ACME_PAYG
    metadata:
      sample7: sample-value4
      sample8: sample-value4
      sample9: sample-value4
    operation: set_meta
  register: output

- name: set vapp metadata output
  debug:
    msg: '{{ output }}'

- name: get vapp metadata
  vcd_vapp:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vapp_name: acme_vapp
    vdc: ACME_PAYG
    operation: get_meta
  register: output

- name: get vapp metadata output
  debug:
    msg: '{{ output }}'

- name: remove vapp metadata
  vcd_vapp:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vapp_name: acme_vapp
    vdc: ACME_PAYG
    metadata:
      sample7: sample-value4
      sample8: sample-value4
      sample9: sample-value4
    operation: remove_meta
  register: output

- name: remove vapp metadata output
  debug:
    msg: '{{ output }}'

- name: add org network
  vcd_vapp:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vapp_name: acme_vapp
    vdc: ACME_PAYG
    network: acme_internal_direct_2
    operation: add_org_network
  register: output

- name: add org network
  debug:
    msg: '{{ output }}'

- name: delete org network
  vcd_vapp:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vapp_name: acme_vapp
    vdc: ACME_PAYG
    network: acme_internal_direct_2
    operation: delete_org_network
  register: output

- name: delete org network
  debug:
    msg: '{{ output }}'

- name: delete vapp
  vcd_vapp:
    vapp_name: test_vapp_1
    vdc: ACME_PAYG
    force: true
    state: absent
  register: output

- name: delete vapp output
  debug:
    msg: '{{ output }}'

- name: delete vapp
  vcd_vapp:
    vapp_name: test_vapp_2
    vdc: ACME_PAYG
    force: true
    state: absent
  register: output

- name: delete vapp output
  debug:
    msg: '{{ output }}'
